config/routes.rb
Rails.application.routes.draw do
  # resources :lines, only: [:index, :show, :new, :edit, :update, :new, :create, :destroy]
  resources :pages, only: [:index, :show, :new, :edit, :update, :new, :destroy, :create]
  # post '/pages', to: 'pages#create', as: '/create/page'
  # resources :users, only: [:index, :show, :new, :edit, :update, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :pages
    belongs_to :shelf
    
    def self.make_with_pages(shelf)
        
        @shelf = shelf

        ref_string = "abcdefghijlmnoprstuvyz ,."
        string = ""
        12.times do
            i = rand(0..24)
            string << ref_string[i]
        end
        spine = string.split('').shuffle.join
        @book = Book.create(spine: spine)

        35.times do
            Page.make_with_lines(@book)
        end

        @shelf.books << @book
        @book.save
        @book
    end
    
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    has_many :walls
    # has_many :jaunts
    # has_many :users, through: :jaunts

    def self.make_with_walls
    
        @gallery = Gallery.create

        4.times do
            Wall.make_with_shelves(@gallery)
        end

        @gallery.save
        @gallery

    end

end

app/models/jaunt.rb
class Jaunt < ApplicationRecord
    # belongs_to :gallery
    belongs_to :user
end

app/models/line.rb
class Line < ApplicationRecord
    belongs_to :page

    def self.make_with_text(page)
        
        @page = page
        @line = Line.new
        
        string = ""
        ref_string = "abcdefghijlmnoprstuvyz ,."
        80.times do
            i = rand(0..24)
            string << ref_string[i]
        end
        @line[:text] = string.split('').shuffle.join
        @page.lines << @line
        
        @line.save
        @line
    end

end

app/models/page.rb
class Page < ApplicationRecord
    has_many :lines
    belongs_to :book

    def self.make_with_lines(book)
       
        @book = book
        @page = Page.create

        40.times do
            Line.make_with_text(@page)
        end

        @book.pages << @page
        @page.save
        @page
    end

end

app/models/shelf.rb
class Shelf < ApplicationRecord
    has_many :books
    belongs_to :wall

    def self.make_with_books(wall)
    
        @wall = wall
        @shelf = Shelf.create

        35.times do
            Book.make_with_pages(@shelf)
        end

        @wall.shelves << @shelf
        @shelf.save
        @shelf   
    end
end

app/models/user.rb
class User < ApplicationRecord
    # has_many :pages
    # has_many :lines, through: :pages
    has_many :jaunts
    # has_many :galleries, through: :jaunts

end

app/models/wall.rb
class Wall < ApplicationRecord
    has_many :shelves
    belongs_to :gallery

    def self.make_with_shelves(gallery)
        
        @gallery = gallery
        @wall = Wall.create

        5.times do
            Shelf.make_with_books(@wall)
        end

        @gallery.walls << @wall
        @wall.save
        @wall
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
    # byebug
    @page = Page.find_by_id(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    # byebug
    Page.make_with_lines
    @page = Page.all.last
    # byebug
    redirect_to page_path(@page)
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlankLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lines/edit.html.erb
<h1>Line#edit</h1>
<p>Find me in app/views/line/edit.html.erb</p>

app/views/lines/index.html.erb
<h1>Line#index</h1>
<p>Find me in app/views/line/index.html.erb</p>

app/views/lines/new.html.erb
<h1>Line#new</h1>
<p>Find me in app/views/line/new.html.erb</p>

app/views/lines/show.html.erb
<h1>Line#show</h1>
<p>Find me in app/views/line/show.html.erb</p>

app/views/pages/edit.html.erb
<h1>Page#edit</h1>
<p>Find me in app/views/page/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Page#index</h1>
<p>Find me in app/views/page/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Page#new</h1>

<%= form_for @page do |f| %>
    <%= f.submit "Make a new page!" %>
<% end %>
 

app/views/pages/show.html.erb
<center><%= link_to "Make a new page", new_page_path %>
<br>
<br>
<h1>Page <%= @page.id %> </h1>
<% @page.lines.each do |line| %>
    <%= line.text %><br>
<% end %></center>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>